accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("home", RedirectView.as_view(pattern_name="home")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView, ReceiptCreateView, ExpenseCategoryListView, AccountListView, ExpenseCategoryCreateView, AccountCreateView
)

urlpatterns = [
    path('', ReceiptListView.as_view(), name='home'), #the empty string refers to the app name
    path('create/', ReceiptCreateView.as_view(), name='create_receipt'),
    path("categories/", ExpenseCategoryListView.as_view(), name="list_categories"),
    path("accounts/", AccountListView.as_view(), name="list_account"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_categories",
    ),
    path(
        "accounts", #this is the path to the browser
        AccountCreateView.as_view(), #pulls in the model if it's a function view you write the function name
        name="create_account", #we give it this name - can use it in the view e.g. return redirect
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, related_name='categories', 
    on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(USER_MODEL, related_name='accounts', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(USER_MODEL, related_name='receipts', on_delete=models.CASCADE)
    category = models.ForeignKey(ExpenseCategory, related_name='receipts', on_delete=models.CASCADE)
    account = models.ForeignKey(Account, related_name='receipts',on_delete=models.CASCADE, null=True)

accounts/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.views.generic.edit import CreateView

from receipts.models import Account

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password1')
            user = User.objects.create(
                username=username,
                password=password
            )
            user.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Receipt, ExpenseCategory, Account
from django.views.generic.edit import CreateView

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/lists.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expense_categories.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/create_expensecategory.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("/receipts/categories/")

class AccountCreateView(CreateView):
    model = Account
    template_name = 'receipts/create.html' #directory path name to the template has to match
    fields = ['name', 'number']

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("create_account") #URL path which is the name we give it in URL patterns

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenses: the Web App!</title>
  
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% endif %}
        {% if user.is_authenticated == False %}
        <li>
          <a href="{% url 'signup' %}">Signup</a>
          <a href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% block pagination %}
    {% endblock pagination %}
  </header>
  {% block content %}
  {% endblock content %}
</body>

</html>

receipts/templates/receipts/accounts.html
{% extends "base.html" %} {% block content %}
<h1>My Accounts</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for account in account_list %}
    <tr>
      <td>{{ account.name }}</td>
      <td>{{ account.number }}</td>
      <td>{{account|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="narrow-form">
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
</main>
{% endblock content %}

receipts/templates/receipts/create_expensecategory.html
{% extends "base.html" %} {% block content %}
<main>
<div>
  <h1>Create Category</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p}}
    <button type="submit">Create</button>
  </form>
</div>
</main>
{% endblock content %}

receipts/templates/receipts/expense_categories.html
{% extends "base.html" %} 

{% block content %}
<a href="{% url 'create_categories' %}">Create</a>
<main>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for category in expensecategory_list %}
      <tr>
        <td>{{category.name}}</td>
        <td>{{category.receipts.all | length }}</td>
      
      </tr>
  </tbody>
  {% endfor %}
</table>
</main>
{% endblock content %}

receipts/templates/receipts/lists.html
{%extends "../base.html"%}
{% block content %}

  <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
              <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
              </tr>
            </thead>
            <tbody>
                {% for receipt in receipt_list %}
                  <tr>
                    <td>{{receipt.vendor}}</td>
                    <td>{{receipt.total}}</td>
                    <td>{{receipt.tax}}</td>
                    <td>{{receipt.date|date:'m-d-Y'}}</td>
                    <td>{{receipt.category}}</td>
                    <td>{{receipt.account}}</td>
                  </tr>
              </tbody>
              {% endfor %}
        </table>
  </main>
</body>

{% endblock %}